[build]
target = "thumbv6m-none-eabi"

rustflags = [
    # Links the memory.x file for proper memory layout.
    "-C", "link-arg=-Tlink.x",

    # Code-size optimizations.
    "-C", "no-vectorize-loops",
]

[target.thumbv6m-none-eabi]
runner = "elf2uf2-rs -d"
